Added an if statement to check when the image has been generated or not

diff --git a/templates/autolauncher-build.yml b/templates/autolauncher-build.yml
--- a/templates/autolauncher-build.yml
+++ b/templates/autolauncher-build.yml
@@ -87,25 +87,27 @@ build_image_mn5:
     - scp -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key ${OPENSTACK_USER}@${OPENSTACK_HOST}:${FINAL_DIR}/build.log autolauncher-output/
     - scp -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key ${OPENSTACK_USER}@${OPENSTACK_HOST}:${FINAL_DIR}/pip_freeze.txt autolauncher-output/
 
-    - echo "${FINAL_IMAGE_PATH}"
-    - echo "${FINAL_DIR}/build.log"
-    - echo "${FINAL_DIR}/pip_freeze.txt"
-
     # Send image to GPFS
     - |
       ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key ${OPENSTACK_USER}@${OPENSTACK_HOST} "
-        sudo mkdir -p ${REMOTE_OUTPUT_PATH} &&
-        sudo cp ${FINAL_IMAGE_PATH} ${REMOTE_OUTPUT_PATH}/ &&
-        sudo cp ${FINAL_DIR}/build.log ${REMOTE_OUTPUT_PATH}/ &&
-        sudo cp ${FINAL_DIR}/pip_freeze.txt ${REMOTE_OUTPUT_PATH}/ &&
-        sudo cp ${REMOTE_DEF_PATH} ${REMOTE_OUTPUT_PATH}/recipe.def
+        if [ -f ${FINAL_IMAGE_PATH} ]; then
+          sudo mkdir -p ${REMOTE_OUTPUT_PATH} &&
+          sudo cp ${FINAL_IMAGE_PATH} ${REMOTE_OUTPUT_PATH}/ &&
+          sudo cp ${FINAL_DIR}/build.log ${REMOTE_OUTPUT_PATH}/ &&
+          sudo cp ${FINAL_DIR}/pip_freeze.txt ${REMOTE_OUTPUT_PATH}/ &&
+          sudo cp ${REMOTE_DEF_PATH} ${REMOTE_OUTPUT_PATH}/recipe.def &&
+          sudo rm -rf ${FINAL_DIR}
+        else
+          echo '[ERROR]: Singularity image was not created.' >&2
+          exit 1
+        fi
       "
-    # TODO: If success remove everything from OpenStack VM (we will do this later)
+
     - |
       echo "┌"
       echo "|"
       echo "|      Singularity image saved to GPFS: "
-      echo "|      ${REMOTE_OUTPUT_PATH}/{SHORT_SHA}.sif "
+      echo "|      ${REMOTE_OUTPUT_PATH}/${SHORT_SHA}.sif "
       echo "|"
       echo "|      Python dependencies stored in: "
       echo "|      ${REMOTE_OUTPUT_PATH}/pip_freeze.txt "
